# pytest.ini - Pytest configuration file

[pytest]
#=================================================== Find test =========================================================
#  Файлы с тестами (default)
python_files = test_*.py *_test.py

# Классы с тестами (default)
python_classes = Test*

# Функции (методы) с тестами (default)
python_functions = test_*
#=======================================================================================================================
