# pytest.ini - Pytest configuration file

[pytest]

#=================================================== Find test =========================================================
#  Файлы с тестами (default)
python_files = test_*.py *_test.py

# Классы с тестами (default)
python_classes = Test*

# Функции (методы) с тестами (default)
python_functions = test_*

#=================================================== Markers ===========================================================
# Кастомные маркеры (⚠️что бы не вылазило PytestUnknownMarkWarning ========= warnings summary ========)
markers =
    smoke: Smoke тесты
    regression: Регрессионные тесты
    --------------
    users: Тесты, связанные с пользователями
    auth: Тесты, связанные с авторизацией (Log in)

;                                                      ИЛИ
#================================================ Warnings ignore ======================================================
# Игнорирование предупреждений (PytestWarning)
filterwarnings =
;    ignore::pytest.PytestUnknownMarkWarning

#=======================================================================================================================
